name: Collaborative project ci/cd pipline

on:
  push:
    branches: [main]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: deploy to digitalocean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        # /* May need to wrrite username and host in script, add nginx and redis */
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd event-planner-collab-team-3-backend
            docker compose down
            git pull origin main
            docker compose up --detach
